# Generated by Django 5.1.5 on 2026-03-17 15:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Номер брони')),
                ('start_at', models.DateTimeField(verbose_name='Начало аренды')),
                ('end_at', models.DateTimeField(verbose_name='Плановый возврат')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий клиента')),
                ('quoted_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Предварительная стоимость')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Залог')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтвержден'), ('cancelled', 'Отменен'), ('expired', 'Истек'), ('active', 'Активная аренда'), ('completed', 'Завершен')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.bike')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.pickuplocation')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.tariff')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('kind', models.CharField(choices=[('rental', 'Оплата аренды'), ('deposit', 'Залог'), ('refund', 'Возврат залога'), ('fine', 'Штраф')], max_length=20, verbose_name='Тип платежа')),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('online', 'Онлайн')], default='card', max_length=20, verbose_name='Метод оплаты')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('external_id', models.CharField(blank=True, max_length=120, verbose_name='Внешний ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rentals.booking')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_start_at', models.DateTimeField(blank=True, null=True, verbose_name='Фактическая выдача')),
                ('actual_end_at', models.DateTimeField(blank=True, null=True, verbose_name='Фактический возврат')),
                ('start_condition', models.TextField(blank=True, verbose_name='Состояние при выдаче')),
                ('end_condition', models.TextField(blank=True, verbose_name='Состояние при возврате')),
                ('damage_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Штраф за повреждение')),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Штраф за просрочку')),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая стоимость')),
                ('status', models.CharField(choices=[('ready', 'Подготовлена к выдаче'), ('active', 'Активна'), ('completed', 'Завершена'), ('overdue', 'Просрочена'), ('cancelled', 'Отменена')], default='ready', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental', to='rentals.booking')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_rentals', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_rentals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аренда',
                'verbose_name_plural': 'Аренды',
                'ordering': ['-created_at'],
            },
        ),
    ]
