# Generated by Django 5.1.5 on 2026-03-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='extra_time_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Доплата за превышение времени'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтвержден'), ('cancelled', 'Отменен'), ('expired', 'Неявка / истек'), ('active', 'Активная аренда'), ('completed', 'Завершен')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
