# Generated by Django 5.1.5 on 2026-05-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rental_extra_time_fee_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина отмены'),
        ),
    ]
