# Generated by Django 5.1.5 on 2026-06-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_booking_cancellation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('qr', 'QR-код'), ('card', 'Карта (архив)'), ('online', 'Онлайн (архив)')], default='cash', max_length=20, verbose_name='Метод оплаты'),
        ),
    ]
