from django.urls import path
from .views import (
    HomePageView,
    TermsView,
    PrivacyPolicyView,
    ContractTemplateView,
    UserDashboardView,
    OperatorDashboardView,
    RevenueListView,
    AnalyticsView,
    AnalyticsBookingsDetailView,
    AnalyticsRentalsDetailView,
    AnalyticsPaymentsDetailView,
    OperatorCustomersListView,
    OperatorCustomerDetailView,
    OperatorBikeListView,
    GenerateCustomerAccessCodeView,
)

urlpatterns = [
    path("terms/", TermsView.as_view(), name="terms"),
    path("privacy/", PrivacyPolicyView.as_view(), name="privacy-policy"),
    path("contract-template/", ContractTemplateView.as_view(), name="contract-template"),
    path("dashboard/", UserDashboardView.as_view(), name="user-dashboard"),
    path("operator/", OperatorDashboardView.as_view(), name="operator-dashboard"),
    path("operator/bikes/", OperatorBikeListView.as_view(), name="operator-bikes"),
    path("operator/customers/", OperatorCustomersListView.as_view(), name="operator-customers"),
    path("operator/customers/<int:pk>/", OperatorCustomerDetailView.as_view(), name="operator-customer-detail"),
    path("operator/customers/<int:pk>/access-code/", GenerateCustomerAccessCodeView.as_view(), name="operator-customer-access-code"),
    path("operator/revenue/", RevenueListView.as_view(), name="operator-revenue"),
    path("operator/analytics/", AnalyticsView.as_view(), name="operator-analytics"),
    path("operator/analytics/bookings/", AnalyticsBookingsDetailView.as_view(), name="analytics-bookings"),
    path("operator/analytics/rentals/", AnalyticsRentalsDetailView.as_view(), name="analytics-rentals"),
    path("operator/analytics/payments/", AnalyticsPaymentsDetailView.as_view(), name="analytics-payments"),
]
