# Generated by Django 5.1.5 on 2026-03-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='next_booking_hourly_surcharge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Надбавка на следующее бронирование (₽/час)'),
        ),
        migrations.AddField(
            model_name='user',
            name='next_booking_penalty_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина надбавки'),
        ),
    ]
