# Generated by Django 5.1.5 on 2026-03-24 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_next_booking_hourly_surcharge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document_last4',
            field=models.CharField(blank=True, max_length=4, verbose_name='Последние 4 цифры документа'),
        ),
        migrations.AddField(
            model_name='user',
            name='document_type',
            field=models.CharField(blank=True, choices=[('passport', 'Паспорт РФ'), ('foreign_passport', 'Загранпаспорт'), ('driver_license', 'Водительское удостоверение'), ('other', 'Иной документ')], max_length=30, verbose_name='Тип документа'),
        ),
        migrations.AddField(
            model_name='user',
            name='document_verified',
            field=models.BooleanField(default=False, verbose_name='Документ проверен оператором'),
        ),
        migrations.AddField(
            model_name='user',
            name='document_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки документа'),
        ),
        migrations.AddField(
            model_name='user',
            name='document_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_customers', to=settings.AUTH_USER_MODEL, verbose_name='Проверил оператор'),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_data_consent',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку ПД'),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_data_consent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата согласия на обработку ПД'),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted',
            field=models.BooleanField(default=False, verbose_name='Условия аренды приняты'),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата принятия условий'),
        ),
    ]
