# Generated by Django 5.1.5 on 2026-05-07 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_document_last4_user_document_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128, verbose_name='Hash кода')),
                ('expires_at', models.DateTimeField(verbose_name='Действует до')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попытки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_account_access_codes', to=settings.AUTH_USER_MODEL, verbose_name='Код выдал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_access_codes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Код доступа к аккаунту',
                'verbose_name_plural': 'Коды доступа к аккаунтам',
                'ordering': ['-created_at'],
            },
        ),
    ]
