# Generated by Django 5.1.5 on 2026-05-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accountaccesscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vk_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='VK ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='vk_photo_url',
            field=models.URLField(blank=True, verbose_name='VK фото'),
        ),
        migrations.AddField(
            model_name='user',
            name='vk_screen_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='VK короткое имя'),
        ),
    ]
