# Generated by Django 5.1.5 on 2026-05-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_vk_id_user_vk_photo_url_user_vk_screen_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vk_notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='Уведомления VK включены'),
        ),
    ]
