# Generated by Django 5.1.5 on 2026-05-08 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_vk_notifications_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Ссылка')),
                ('level', models.CharField(choices=[('info', 'Информация'), ('success', 'Успешно'), ('warning', 'Важно')], default='info', max_length=20, verbose_name='Тип')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление пользователя',
                'verbose_name_plural': 'Уведомления пользователей',
                'ordering': ['-created_at'],
            },
        ),
    ]
