# Generated by Django 5.1.5 on 2026-05-20 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_email_verified_at_emailverificationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordChangeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128, verbose_name='Hash кода')),
                ('expires_at', models.DateTimeField(verbose_name='Действует до')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попытки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_change_codes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Код смены пароля',
                'verbose_name_plural': 'Коды смены пароля',
                'ordering': ['-created_at'],
            },
        ),
    ]
