# Generated by Django 5.1.5 on 2026-03-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=100, verbose_name='Сущность')),
                ('entity_id', models.CharField(max_length=100, verbose_name='Идентификатор сущности')),
                ('event_type', models.CharField(max_length=100, verbose_name='Тип события')),
                ('payload', models.JSONField(verbose_name='Данные')),
                ('direction', models.CharField(choices=[('to_1c', 'В 1С'), ('from_1c', 'Из 1С')], max_length=20, verbose_name='Направление')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('response_text', models.TextField(blank=True, verbose_name='Ответ системы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Событие синхронизации',
                'verbose_name_plural': 'События синхронизации',
                'ordering': ['-created_at'],
            },
        ),
    ]
