# Generated by Django 5.1.5 on 2026-06-11 14:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('rentals', '0003_booking_cancellation_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254, verbose_name='Получатель')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('body', models.TextField(verbose_name='Текст письма')),
                ('kind', models.CharField(blank=True, max_length=100, verbose_name='Тип письма')),
                ('deduplication_key', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Ключ защиты от дублей')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попыток')),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Следующая попытка')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Доставка письма',
                'verbose_name_plural': 'Доставка писем',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingNotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100, verbose_name='Событие')),
                ('audience', models.CharField(choices=[('customer', 'Клиент'), ('operator', 'Оператор')], max_length=20, verbose_name='Получатель')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_events', to='rentals.booking', verbose_name='Бронь')),
            ],
            options={
                'verbose_name': 'Событие уведомления по брони',
                'verbose_name_plural': 'События уведомлений по броням',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('booking', 'event', 'audience'), name='unique_booking_notification_event')],
            },
        ),
    ]
