# Generated by Django 5.1.5 on 2026-03-17 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория велосипеда',
                'verbose_name_plural': 'Категории велосипедов',
            },
        ),
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название точки')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('opening_hours', models.CharField(blank=True, max_length=120, verbose_name='Часы работы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Точка выдачи',
                'verbose_name_plural': 'Точки выдачи',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название тарифа')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за час')),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за сутки')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Залог')),
                ('late_fee_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Штраф за час просрочки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('serial_number', models.CharField(max_length=120, unique=True, verbose_name='Серийный номер')),
                ('frame_size', models.CharField(blank=True, max_length=50, verbose_name='Размер рамы')),
                ('wheel_size', models.CharField(blank=True, max_length=50, verbose_name='Диаметр колеса')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Цвет')),
                ('status', models.CharField(choices=[('available', 'Доступен'), ('reserved', 'Забронирован'), ('in_rent', 'В аренде'), ('service', 'На обслуживании'), ('retired', 'Списан')], default='available', max_length=20, verbose_name='Статус')),
                ('condition_notes', models.TextField(blank=True, verbose_name='Комментарий по состоянию')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='bikes/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bikes', to='catalog.bikecategory')),
                ('current_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bikes', to='catalog.pickuplocation')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bikes', to='catalog.tariff')),
            ],
            options={
                'verbose_name': 'Велосипед',
                'verbose_name_plural': 'Велосипеды',
            },
        ),
    ]
